export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';
export const GET_SETTING_LIST = 'GET_SETTING_LIST';

// Add SETTING
export const POST_SETTING = 'POST_SETTING';
export const POST_SETTING_SUCCESS = 'POST_SETTING_SUCCESS';
export const POST_SETTING_FAILED = 'POST_SETTING_FAILED';
