export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';
export const GET_SERVICE_LIST = 'GET_SERVICE_LIST';

// Add SERVICE
export const POST_SERVICE = 'POST_SERVICE';
export const POST_SERVICE_SUCCESS = 'POST_SERVICE_SUCCESS';
export const POST_SERVICE_FAILED = 'POST_SERVICE_FAILED';

// Edit SERVICE
export const PUT_SERVICE = 'PUT_SERVICE';
export const PUT_SERVICE_SUCCESS = 'PUT_SERVICE_SUCCESS';
export const PUT_SERVICE_FAILED = 'PUT_SERVICE_FAILED';

// Delete SERVICE
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAILED = 'DELETE_SERVICE_FAILED';
