export const ModuleTypes = {
    Heading1: 'heading 1',
    Heading2: 'heading 2',
    Heading3: 'heading 3',
    Italic: 'italic',
    Bold: 'bold',
    Indent: 'indent',
    Underline: 'underline',
    Paragraph: 'paragraph',
    FontSize: 'font-size',
    Emoji: 'emoji',
    Image: 'image',
    Video: 'video',
    Center: 'center',
    Left: 'left',
    Right: 'right',
    Unordered: 'unordered',
    Ordered: 'ordered',
    Undo: 'undo',
    Redo: 'redo',
};
