export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';
export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_STAFF_LIST = 'GET_STAFF_LIST';

export const ADD_NEW_STAFF = 'ADD_NEW_STAFF';
export const ADD_NEW_STAFF_TO_LOCAL = 'ADD_NEW_STAFF_TO_LOCAL';
