export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';
export const GET_CUSTOMER = 'GET_CUSTOMER';

// Add CUSTOMER
export const POST_CUSTOMER = 'POST_CUSTOMER';
export const POST_CUSTOMER_SUCCESS = 'POST_CUSTOMER_SUCCESS';
export const POST_CUSTOMER_FAILED = 'POST_CUSTOMER_FAILED';

// Edit CUSTOMER
export const PUT_CUSTOMER = 'PUT_CUSTOMER';
export const PUT_CUSTOMER_SUCCESS = 'PUT_CUSTOMER_SUCCESS';
export const PUT_CUSTOMER_FAILED = 'PUT_CUSTOMER_FAILED';

// Delete CUSTOMER
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAILED = 'DELETE_CUSTOMER_FAILED';
