// Actions
export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';
export const GET_TESTIMONIAL_LIST = 'GET_TESTIMONIAL_LIST';

// Get Single testimonial
export const GET_TESTIMONIAL = 'GET_TESTIMONIAL';
export const GET_TESTIMONIAL_SUCCESS = 'GET_TESTIMONIAL_SUCCESS';
export const GET_TESTIMONIAL_FAILED = 'GET_TESTIMONIAL_FAILED';

// Add Blog
export const POST_TESTIMONIAL = 'POST_ASSET';
export const POST_TESTIMONIAL_SUCCESS = 'POST_TESTIMONIAL_SUCCESS';
export const POST_TESTIMONIAL_FAILED = 'POST_TESTIMONIAL_FAILED';

// Edit Blog
export const PUT_TESTIMONIAL = 'PUT_TESTIMONIAL';
export const PUT_TESTIMONIAL_SUCCESS = 'PUT_TESTIMONIAL_SUCCESS';
export const PUT_TESTIMONIAL_FAILED = 'PUT_TESTIMONIAL_FAILED';

// Delete Blog
export const DELETE_TESTIMONIAL = 'DELETE_TESTIMONIAL';
export const DELETE_TESTIMONIAL_SUCCESS = 'DELETE_TESTIMONIAL_SUCCESS';
export const DELETE_TESTIMONIAL_FAILED = 'DELETE_TESTIMONIAL_FAILED';
