export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';
export const GET_BOOKING = 'GET_BOOKING';

// Add Booking
export const POST_BOOKING = 'POST_BOOKING';
export const POST_BOOKING_SUCCESS = 'POST_BOOKING_SUCCESS';
export const POST_BOOKING_FAILED = 'POST_BOOKING_FAILED';

// Edit Booking
export const PUT_BOOKING = 'PUT_BOOKING';
export const PUT_BOOKING_SUCCESS = 'PUT_BOOKING_SUCCESS';
export const PUT_BOOKING_FAILED = 'PUT_BOOKING_FAILED';

// Delete Booking
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_FAILED = 'DELETE_BOOKING_FAILED';

// Delete Bookings
export const DELETE_MANY_BOOKING = 'DELETE_MANY_BOOKINGS';
export const DELETE_MANY_BOOKING_SUCCESS = 'DELETE_MANY_BOOKINGS_SUCCESS';
export const DELETE_MANY_BOOKING_FAILED = 'DELETE_MANY_BOOKINGS_FAILED';
