export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';
export const GET_ASSIGN_LIST = 'GET_ASSIGN_LIST';

// Edit ASSIGN
export const PUT_ASSIGN = 'PUT_ASSIGN';
export const PUT_ASSIGN_SUCCESS = 'PUT_ASSIGN_SUCCESS';
export const PUT_ASSIGN_FAILED = 'PUT_ASSIGN_FAILED';
